# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.viewport = QtWidgets.QLabel(self.centralwidget)
        self.viewport.setGeometry(QtCore.QRect(336, 6, 761, 671))
        self.viewport.setAutoFillBackground(False)
        self.viewport.setObjectName("viewport")

        self.objectsList = QtWidgets.QListWidget(self.centralwidget)
        self.objectsList.setGeometry(QtCore.QRect(10, 10, 311, 221))
        self.objectsList.setObjectName("objectsList")

        self.pointRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.pointRadioButton.setGeometry(QtCore.QRect(10, 240, 112, 23))
        self.pointRadioButton.setObjectName("radioButton")

        self.lineRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.lineRadioButton.setGeometry(QtCore.QRect(100, 240, 112, 23))
        self.lineRadioButton.setObjectName("radioButton_2")

        self.polygonRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.polygonRadioButton.setGeometry(QtCore.QRect(210, 240, 112, 23))
        self.polygonRadioButton.setObjectName("radioButton_3")

        self.confirmButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.select())
        self.confirmButton.setGeometry(QtCore.QRect(10, 290, 89, 25))
        self.confirmButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 290, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 290, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1097, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def select(self):
        if self.pointRadioButton.isChecked():
            self.viewport.setText("ponto")
        elif self.lineRadioButton.isChecked():
            self.viewport.setText("reta")
        elif self.polygonRadioButton.isChecked():
            self.viewport.setText("polygon")
        else:
            self.viewport.setText("select one")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.viewport.setText(_translate("MainWindow", "VIEWPORT"))
        self.pointRadioButton.setText(_translate("MainWindow", "Point"))
        self.lineRadioButton.setText(_translate("MainWindow", "Line"))
        self.polygonRadioButton.setText(_translate("MainWindow", "Polygon"))
        self.confirmButton.setText(_translate("MainWindow", "Confirmar"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancelar"))
        self.pushButton_3.setText(_translate("MainWindow", "Remover"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
